language: node_js

env:
     - DB=postgresql://postgres@localhost:5432/registrations
node_js:
        - "10.4.0"

before_script:
  - psql -c 'create database  registrations;' -U postgres
  - psql -U postgres -d registrations -a -f registrationdb-script.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2
